name: polyscan

on:
  workflow_dispatch:

jobs:
  polyscan:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v5

      - name: polyscan
        uses: sraisl/polyscan-action@v5
        with:
          target: "."
          engines: "semgrep,spotbugs,trivy,detekt,gitleaks"
          max-critical: "0"
          max-high: "0"
          max-medium: "50"
          gate: "true"
          sarif: "true"
          sbom: "true"
          upload-artifacts: "true"
